@php $hide_title = true; @endphp
@extends('layouts.public')


@section('title', 'Honest Ipsum')
@section('description', 'Honest Ipsum is a replacement for Lorem Ipsum. It was created to alleviate the confusion some clients experience when they see a foreign language all over their website or poster. The filler text generated by this tool is free to be used by designers and developers.')

@section('head')
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
	  (adsbygoogle = window.adsbygoogle || []).push({
	    google_ad_client: "ca-pub-5140337642048174",
	    enable_page_level_ads: true
	  });
	</script>
@stop

@section('content')

	<div class="jumbotron home">
		<div class="container text-center">
			<h1>HONEST IPSUM</h1>
			<h2 id="buzz1" class="buzzword script">"The site looks great, I just don't know why some of the words are in Spanish!"</h2>
			<h2 id="buzz2" class="buzzword script">"Looks great to me...apart from your Latin which is lousy!"</h3>
			<h2 id="buzz3" class="buzzword script">"Hey looks nice, but the text content is obviously wrong...please fix it."</h2>
		</div>
	</div>

	<div class="container">

		<div class="row">
			<div class="col-sm-12">
				<h2>Meet Honest Ipsum</h2>
				<p>If the last thing you want to do is explain the history of why Latin text is being used as a placeholder in your design, this is the tool for you! Feel free to copy and paste this text and use it as a placeholder on your next project!</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-lg-4">
				<h2>Online Generator</h2>
				<p>Just choose how many items to generate, their length in words, and what type of delimeter to use then hit generate.

				<form action="/honestipsum" method="post">
					{{csrf_field()}}

					@if(count($errors->all()))
					<p class="text-danger">{{$errors->first()}}</p>
					@endif

					<div class="form-group">
						<div class="input-group input-group-lg">
							<label for="count-input" class="input-group-addon">Paragraphs</label>
						  	<input id="count-input" type="number" name="count" min="1" max="1000" class="text-right form-control" placeholder="Paragraphs" value="{{old('count', $count)}}">
						</div> <!-- input group -->
					</div><!-- form group -->

					<div class="form-group">
						<div class="input-group input-group-lg">
							<label for="length-input" class="input-group-addon">Words per Paragraph *</label>
						  	<input id="length-input" type="number" name="length" min="1" max="1000" class="text-right form-control" placeholder="Paragraph Length" value="{{old('length', $length)}}">
						</div> <!-- input group -->
					</div><!-- form group -->

					<div class="form-group">
						<div class="btn-group input-group-lg">
						  	<span data-format="nl" class="format-select btn btn-default btn-lg {{active(old('format',$format), 'nl')}}">\n</span>
					      	<span data-format="br" class="format-select btn btn-default btn-lg {{active(old('format',$format), 'br')}}">&lt;br&gt;</span>
					        <span data-format="p" class="format-select btn btn-default btn-lg {{active(old('format',$format), 'p')}}">&lt;p&gt;</span>
						</div>
						<input id="format-input" type="hidden" name="format" value="{{$format}}">

						<button type="submit" class="btn btn-success btn-lg pull-right">Generate</button>
					</div><!-- form group -->

				</form>

				<p>* The number of words in the paragraph should be within about 10 words of what you request.</p>

			</div> <!-- col -->

			<div class="col-md-6 col-lg-8">
				<h2>API Documentation</h2>
				<p>You can use the simple API as well, a GET request to:</p>
				<pre>http://johnclendvoy.ca/honestipsum/api?count=1&length=100&format=p</pre>

				<p>There are 3 simple parameters:</p>

				<dl class="dl-horizontal">
					<dt><code>count</code></dt> 
					<dd>How many elements to generate. Must be an integer between 1 and 500. Default: 2</dd>
					<dt><code>length</code></dt> 
					<dd>How many words are in each element. Must be an integer between 1 and 1000. Note that the exact number of words in each element may be slightly less than the entered value, it gets as close as possible without writing any sentence fragments. Default: 50</dd>
					<dt><code>format</code></dt>
					<dd>How should the elements be output? Accepted values are <code>p</code> (surrounded by &lt;p&gt; tags), <code>br</code> (followed by a &lt;br&gt; tag), <code>nl</code> ( followed by a newline character). Default: p</dd>
				</dl>
				<p>Support for more element formats is in progress.</p>
				
			</div> <!-- col -->

		</div>

		<div class="row">

			<div class="col-md-12">
			<h2>Example Output</h2>
			</div>

			<div class="col-md-6">
				{!!$ipsum!!}
			</div>

			<div class="col-md-6">
				<pre id="copyable">{{$ipsum}}</pre>
			</div>


		</div> <!-- row -->

		<div class="row">
				<div class="col-sm-12">
					<h2>Credits</h2>
					<p>Thank you to the following reddit users at <a href="http://reddit.com/r/web_design">/r/web_design</a> for contributing content and or suggestions to improve this generator!</p>

					<p>
						@foreach($credits as $credit)
						<a href="http://reddit.com/u/{{$credit}}">/u/{{$credit}}</a>@unless($loop->last ),@endunless
						@endforeach
					</p>

				</div>
		</div>
	</div> <!-- container -->

	@stop

 @section('js')

	<script src="/js/home_animation.js"></script>

	<script>
		$(document).ready(function(){
			$('.format-select').click(function(){
				var clicked = $(this);

				$('.format-select').each(function(){
					$(this).removeClass('active');
				});

				clicked.addClass('active');
				var format = clicked.data('format');
				$('#format-input').val(format);
			});
		});
	</script>
@stop

